//! Folder icons from the folder pack (assets/folder-icons): picked by the
//! folder's name (src, tests, .github, ...), else the plain folder. Each
//! one comes in two shapes — open and shut — and the row fades from one to
//! the other as the folder opens. Like the file icons (file_icon.zig) they
//! are SVGs, rasterized with nanosvg the first time they are drawn, for
//! the display's density and the zoom.
const std = @import("std");
const rl = @import("raylib");
const theme = @import("../../theme/lib/theme.zig");

/// Width and height of an icon, in UI units (the pack draws on 16x16).
pub const size: f32 = 16;

/// What a folder shows in front of its name (Settings): the same plain
/// folder for every one of them, the icon for its name, or nothing.
pub const Mode = enum { same, by_name, none };
pub var mode: Mode = .by_name;

/// Whether folders draw an icon at all.
pub fn shown() bool {
    return mode != .none;
}

/// The pack's icons, by file name without `.svg`; each also has a `-1`
/// file, which is the shut shape.
const Icon = enum {
    folder,
    acf,
    acre,
    adapter,
    addon,
    admin,
    adr,
    agda,
    alacritty,
    amplication,
    android,
    angular,
    animations,
    ansible,
    api,
    apollo,
    app,
    appstore,
    archetype,
    archive,
    article,
    arttext,
    atom,
    audio,
    aurelia,
    automator,
    aws,
    @"azure-devops",
    @"azure-pipelines",
    base,
    bazaar,
    benchmark,
    bitcoin,
    bloc,
    blueprint,
    bower,
    buildkite,
    cabal,
    cake,
    cart,
    channels,
    chef,
    ci,
    circleci,
    class,
    client,
    cluster,
    cmake,
    cnab,
    cobol,
    codesandbox,
    components,
    composer,
    config,
    connection,
    constants,
    container,
    content,
    contract,
    controllers,
    core,
    coverage,
    crates,
    cron,
    cubit,
    cue,
    custom,
    cvs,
    cypress,
    dapr,
    db,
    debian,
    debug,
    decorators,
    delta,
    deno,
    dependabot,
    devcontainer,
    dist,
    docker,
    docs,
    domain,
    download,
    dropbox,
    dub,
    dump,
    dvc,
    e2e,
    elastic,
    electron,
    elixir,
    emacs,
    env,
    @"error",
    events,
    examples,
    exclude,
    expo,
    faq,
    fastlane,
    features,
    firebase,
    fixtures,
    flow,
    fonts,
    functions,
    gcloud,
    generated,
    git,
    github,
    gitlab,
    global,
    gradle,
    graphql,
    grunt,
    guard,
    gulp,
    hasura,
    haxelib,
    helm,
    helper,
    home,
    hook,
    husky,
    i18n,
    icons,
    idea,
    images,
    include,
    info,
    init,
    injection,
    ios,
    istanbul,
    java,
    jest,
    jinja,
    job,
    js,
    json,
    jwt,
    keys,
    kivy,
    kotlin,
    kubernetes,
    kustomize,
    layouts,
    less,
    lib,
    linux,
    logs,
    lua,
    mac,
    mailers,
    main,
    maps,
    markdown,
    math,
    maven,
    mercurial,
    messages,
    meta,
    meteor,
    middleware,
    mjml,
    mobile,
    mocks,
    modals,
    models,
    molecules,
    mongo,
    moon,
    navigation,
    next,
    node,
    notebooks,
    notification,
    nuget,
    nuxt,
    openshift,
    osx,
    other,
    packages,
    pdf,
    perl,
    php,
    pinia,
    pipe,
    platformio,
    playwright,
    plugin,
    posts,
    prisma,
    private,
    project,
    projects,
    protobuf,
    providers,
    python,
    quantum,
    quasar,
    queries,
    queue,
    react,
    recoil,
    redhat,
    redis,
    redux,
    @"redux-actions",
    @"redux-epics",
    @"redux-reducers",
    @"redux-sagas",
    @"redux-stores",
    redwood,
    resolver,
    resource,
    reviews,
    root,
    routes,
    ruby,
    rules,
    rust,
    sass,
    scala,
    scratch,
    screens,
    scripts,
    security,
    server,
    shader,
    shared,
    sql,
    src,
    sso,
    stack,
    stencil,
    storage,
    storyblok,
    storybook,
    strategy,
    styles,
    stylus,
    sublime,
    supabase,
    svelte,
    svg,
    svn,
    sync,
    syntax,
    target,
    taskfile,
    tasks,
    tauri,
    tech,
    temp,
    terraform,
    tests,
    textmate,
    themes,
    tools,
    trait,
    ts,
    unity,
    upload,
    users,
    vagrant,
    venv,
    vercel,
    verdaccio,
    video,
    viewmodel,
    views,
    vim,
    vitepress,
    vm,
    vs,
    vscode,
    vue,
    vuepress,
    vuex,
    web,
    webpack,
    windows,
    wine,
    woocommerce,
    woodpecker,
    wordpress,
    xstate,
    yarn,
};

const pack = "../../../assets/folder-icons/";
const Svgs = struct { open: []const u8, shut: []const u8 };
const svgs = blk: {
    const fields = @typeInfo(Icon).@"enum".fields;
    var list: [fields.len]Svgs = undefined;
    @setEvalBranchQuota(200_000);
    for (fields, 0..) |f, i| {
        list[i] = .{
            .open = @embedFile(pack ++ f.name ++ ".svg"),
            .shut = @embedFile(pack ++ f.name ++ "-1.svg"),
        };
    }
    break :blk list;
};

/// Folder names the pack spells differently (lowercase).
const by_alias = std.StaticStringMap(Icon).initComptime(.{
    .{ "test", .tests },
    .{ "__tests__", .tests },
    .{ "spec", .tests },
    .{ "specs", .tests },
    .{ "img", .images },
    .{ "image", .images },
    .{ "icon", .icons },
    .{ "build", .dist },
    .{ "out", .dist },
    .{ "output", .dist },
    .{ "node_modules", .packages },
    .{ "vendor", .packages },
    .{ "deps", .packages },
    .{ "dependencies", .packages },
    .{ "public", .web },
    .{ "static", .web },
    .{ "www", .web },
    .{ "site", .web },
    .{ "doc", .docs },
    .{ "documentation", .docs },
    .{ "log", .logs },
    .{ "util", .helper },
    .{ "utils", .helper },
    .{ "helpers", .helper },
    .{ "hooks", .hook },
    .{ "model", .models },
    .{ "modal", .modals },
    .{ "view", .views },
    .{ "route", .routes },
    .{ "controller", .controllers },
    .{ "provider", .providers },
    .{ "locale", .i18n },
    .{ "locales", .i18n },
    .{ "lang", .i18n },
    .{ "languages", .i18n },
    .{ "translations", .i18n },
    .{ "translation", .i18n },
    .{ "videos", .video },
    .{ "sound", .audio },
    .{ "sounds", .audio },
    .{ "music", .audio },
    .{ "font", .fonts },
    .{ "script", .scripts },
    .{ "style", .styles },
    .{ "css", .styles },
    .{ "tool", .tools },
    .{ "example", .examples },
    .{ "sample", .examples },
    .{ "samples", .examples },
    .{ "tmp", .temp },
    .{ "cache", .temp },
    .{ "resources", .resource },
    .{ "asset", .resource },
    .{ "assets", .resource },
    .{ "type", .ts },
    .{ "types", .ts },
    .{ "typings", .ts },
    .{ "interfaces", .contract },
    .{ "query", .queries },
    .{ "feature", .features },
    .{ "page", .screens },
    .{ "pages", .screens },
    .{ "key", .keys },
    .{ "secrets", .keys },
    .{ "cert", .keys },
    .{ "certs", .keys },
    .{ "task", .tasks },
    .{ "jobs", .job },
    .{ "worker", .job },
    .{ "workers", .job },
    .{ "bin", .tools },
    .{ "cmd", .tools },
    .{ "cli", .tools },
    .{ "test_helpers", .tests },
    .{ "fixture", .fixtures },
    .{ "mock", .mocks },
    .{ "migration", .queries },
    .{ "migrations", .queries },
    .{ "database", .db },
    .{ "data", .db },
    .{ "store", .storage },
    .{ "stores", .storage },
    .{ "state", .storage },
    .{ "event", .events },
    .{ "error_pages", .@"error" },
    .{ "errors", .@"error" },
    .{ "component", .components },
    .{ "constant", .constants },
    .{ "layout", .layouts },
    .{ "middlewares", .middleware },
    .{ "plugins", .plugin },
    .{ "theme", .themes },
    .{ "user", .users },
    .{ "map", .maps },
    .{ "note", .notebooks },
    .{ "notes", .notebooks },
    .{ "uploads", .upload },
    .{ "downloads", .download },
    .{ "post", .posts },
    .{ "review", .reviews },
    .{ "rule", .rules },
    .{ "screen", .screens },
    .{ "service", .server },
    .{ "services", .server },
});

/// Every icon under its own name, so a folder called like one gets it.
const by_name = std.StaticStringMap(Icon).initComptime(.{
    .{ "folder", .folder },
    .{ "acf", .acf },
    .{ "acre", .acre },
    .{ "adapter", .adapter },
    .{ "addon", .addon },
    .{ "admin", .admin },
    .{ "adr", .adr },
    .{ "agda", .agda },
    .{ "alacritty", .alacritty },
    .{ "amplication", .amplication },
    .{ "android", .android },
    .{ "angular", .angular },
    .{ "animations", .animations },
    .{ "ansible", .ansible },
    .{ "api", .api },
    .{ "apollo", .apollo },
    .{ "app", .app },
    .{ "appstore", .appstore },
    .{ "archetype", .archetype },
    .{ "archive", .archive },
    .{ "article", .article },
    .{ "arttext", .arttext },
    .{ "atom", .atom },
    .{ "audio", .audio },
    .{ "aurelia", .aurelia },
    .{ "automator", .automator },
    .{ "aws", .aws },
    .{ "azure-devops", .@"azure-devops" },
    .{ "azure-pipelines", .@"azure-pipelines" },
    .{ "base", .base },
    .{ "bazaar", .bazaar },
    .{ "benchmark", .benchmark },
    .{ "bitcoin", .bitcoin },
    .{ "bloc", .bloc },
    .{ "blueprint", .blueprint },
    .{ "bower", .bower },
    .{ "buildkite", .buildkite },
    .{ "cabal", .cabal },
    .{ "cake", .cake },
    .{ "cart", .cart },
    .{ "channels", .channels },
    .{ "chef", .chef },
    .{ "ci", .ci },
    .{ "circleci", .circleci },
    .{ "class", .class },
    .{ "client", .client },
    .{ "cluster", .cluster },
    .{ "cmake", .cmake },
    .{ "cnab", .cnab },
    .{ "cobol", .cobol },
    .{ "codesandbox", .codesandbox },
    .{ "components", .components },
    .{ "composer", .composer },
    .{ "config", .config },
    .{ "connection", .connection },
    .{ "constants", .constants },
    .{ "container", .container },
    .{ "content", .content },
    .{ "contract", .contract },
    .{ "controllers", .controllers },
    .{ "core", .core },
    .{ "coverage", .coverage },
    .{ "crates", .crates },
    .{ "cron", .cron },
    .{ "cubit", .cubit },
    .{ "cue", .cue },
    .{ "custom", .custom },
    .{ "cvs", .cvs },
    .{ "cypress", .cypress },
    .{ "dapr", .dapr },
    .{ "db", .db },
    .{ "debian", .debian },
    .{ "debug", .debug },
    .{ "decorators", .decorators },
    .{ "delta", .delta },
    .{ "deno", .deno },
    .{ "dependabot", .dependabot },
    .{ "devcontainer", .devcontainer },
    .{ "dist", .dist },
    .{ "docker", .docker },
    .{ "docs", .docs },
    .{ "domain", .domain },
    .{ "download", .download },
    .{ "dropbox", .dropbox },
    .{ "dub", .dub },
    .{ "dump", .dump },
    .{ "dvc", .dvc },
    .{ "e2e", .e2e },
    .{ "elastic", .elastic },
    .{ "electron", .electron },
    .{ "elixir", .elixir },
    .{ "emacs", .emacs },
    .{ "env", .env },
    .{ "error", .@"error" },
    .{ "events", .events },
    .{ "examples", .examples },
    .{ "exclude", .exclude },
    .{ "expo", .expo },
    .{ "faq", .faq },
    .{ "fastlane", .fastlane },
    .{ "features", .features },
    .{ "firebase", .firebase },
    .{ "fixtures", .fixtures },
    .{ "flow", .flow },
    .{ "fonts", .fonts },
    .{ "functions", .functions },
    .{ "gcloud", .gcloud },
    .{ "generated", .generated },
    .{ "git", .git },
    .{ "github", .github },
    .{ "gitlab", .gitlab },
    .{ "global", .global },
    .{ "gradle", .gradle },
    .{ "graphql", .graphql },
    .{ "grunt", .grunt },
    .{ "guard", .guard },
    .{ "gulp", .gulp },
    .{ "hasura", .hasura },
    .{ "haxelib", .haxelib },
    .{ "helm", .helm },
    .{ "helper", .helper },
    .{ "home", .home },
    .{ "hook", .hook },
    .{ "husky", .husky },
    .{ "i18n", .i18n },
    .{ "icons", .icons },
    .{ "idea", .idea },
    .{ "images", .images },
    .{ "include", .include },
    .{ "info", .info },
    .{ "init", .init },
    .{ "injection", .injection },
    .{ "ios", .ios },
    .{ "istanbul", .istanbul },
    .{ "java", .java },
    .{ "jest", .jest },
    .{ "jinja", .jinja },
    .{ "job", .job },
    .{ "js", .js },
    .{ "json", .json },
    .{ "jwt", .jwt },
    .{ "keys", .keys },
    .{ "kivy", .kivy },
    .{ "kotlin", .kotlin },
    .{ "kubernetes", .kubernetes },
    .{ "kustomize", .kustomize },
    .{ "layouts", .layouts },
    .{ "less", .less },
    .{ "lib", .lib },
    .{ "linux", .linux },
    .{ "logs", .logs },
    .{ "lua", .lua },
    .{ "mac", .mac },
    .{ "mailers", .mailers },
    .{ "main", .main },
    .{ "maps", .maps },
    .{ "markdown", .markdown },
    .{ "math", .math },
    .{ "maven", .maven },
    .{ "mercurial", .mercurial },
    .{ "messages", .messages },
    .{ "meta", .meta },
    .{ "meteor", .meteor },
    .{ "middleware", .middleware },
    .{ "mjml", .mjml },
    .{ "mobile", .mobile },
    .{ "mocks", .mocks },
    .{ "modals", .modals },
    .{ "models", .models },
    .{ "molecules", .molecules },
    .{ "mongo", .mongo },
    .{ "moon", .moon },
    .{ "navigation", .navigation },
    .{ "next", .next },
    .{ "node", .node },
    .{ "notebooks", .notebooks },
    .{ "notification", .notification },
    .{ "nuget", .nuget },
    .{ "nuxt", .nuxt },
    .{ "openshift", .openshift },
    .{ "osx", .osx },
    .{ "other", .other },
    .{ "packages", .packages },
    .{ "pdf", .pdf },
    .{ "perl", .perl },
    .{ "php", .php },
    .{ "pinia", .pinia },
    .{ "pipe", .pipe },
    .{ "platformio", .platformio },
    .{ "playwright", .playwright },
    .{ "plugin", .plugin },
    .{ "posts", .posts },
    .{ "prisma", .prisma },
    .{ "private", .private },
    .{ "project", .project },
    .{ "projects", .projects },
    .{ "protobuf", .protobuf },
    .{ "providers", .providers },
    .{ "python", .python },
    .{ "quantum", .quantum },
    .{ "quasar", .quasar },
    .{ "queries", .queries },
    .{ "queue", .queue },
    .{ "react", .react },
    .{ "recoil", .recoil },
    .{ "redhat", .redhat },
    .{ "redis", .redis },
    .{ "redux", .redux },
    .{ "redux-actions", .@"redux-actions" },
    .{ "redux-epics", .@"redux-epics" },
    .{ "redux-reducers", .@"redux-reducers" },
    .{ "redux-sagas", .@"redux-sagas" },
    .{ "redux-stores", .@"redux-stores" },
    .{ "redwood", .redwood },
    .{ "resolver", .resolver },
    .{ "resource", .resource },
    .{ "reviews", .reviews },
    .{ "root", .root },
    .{ "routes", .routes },
    .{ "ruby", .ruby },
    .{ "rules", .rules },
    .{ "rust", .rust },
    .{ "sass", .sass },
    .{ "scala", .scala },
    .{ "scratch", .scratch },
    .{ "screens", .screens },
    .{ "scripts", .scripts },
    .{ "security", .security },
    .{ "server", .server },
    .{ "shader", .shader },
    .{ "shared", .shared },
    .{ "sql", .sql },
    .{ "src", .src },
    .{ "sso", .sso },
    .{ "stack", .stack },
    .{ "stencil", .stencil },
    .{ "storage", .storage },
    .{ "storyblok", .storyblok },
    .{ "storybook", .storybook },
    .{ "strategy", .strategy },
    .{ "styles", .styles },
    .{ "stylus", .stylus },
    .{ "sublime", .sublime },
    .{ "supabase", .supabase },
    .{ "svelte", .svelte },
    .{ "svg", .svg },
    .{ "svn", .svn },
    .{ "sync", .sync },
    .{ "syntax", .syntax },
    .{ "target", .target },
    .{ "taskfile", .taskfile },
    .{ "tasks", .tasks },
    .{ "tauri", .tauri },
    .{ "tech", .tech },
    .{ "temp", .temp },
    .{ "terraform", .terraform },
    .{ "tests", .tests },
    .{ "textmate", .textmate },
    .{ "themes", .themes },
    .{ "tools", .tools },
    .{ "trait", .trait },
    .{ "ts", .ts },
    .{ "unity", .unity },
    .{ "upload", .upload },
    .{ "users", .users },
    .{ "vagrant", .vagrant },
    .{ "venv", .venv },
    .{ "vercel", .vercel },
    .{ "verdaccio", .verdaccio },
    .{ "video", .video },
    .{ "viewmodel", .viewmodel },
    .{ "views", .views },
    .{ "vim", .vim },
    .{ "vitepress", .vitepress },
    .{ "vm", .vm },
    .{ "vs", .vs },
    .{ "vscode", .vscode },
    .{ "vue", .vue },
    .{ "vuepress", .vuepress },
    .{ "vuex", .vuex },
    .{ "web", .web },
    .{ "webpack", .webpack },
    .{ "windows", .windows },
    .{ "wine", .wine },
    .{ "woocommerce", .woocommerce },
    .{ "woodpecker", .woodpecker },
    .{ "wordpress", .wordpress },
    .{ "xstate", .xstate },
    .{ "yarn", .yarn },
});

fn iconFor(name: []const u8) Icon {
    if (mode != .by_name) return .folder;
    var buf: [64]u8 = undefined;
    if (name.len > buf.len) return .folder;
    const n = std.ascii.lowerString(buf[0..name.len], name);
    if (by_name.get(n)) |icon| return icon;
    if (by_alias.get(n)) |icon| return icon;
    // A leading dot is how a folder hides, not part of its name.
    if (n.len > 1 and n[0] == '.') {
        if (by_name.get(n[1..])) |icon| return icon;
        if (by_alias.get(n[1..])) |icon| return icon;
    }
    return .folder;
}

/// Rasterized icons, made on first use and remade when the pixel size
/// changes. Open and shut are kept apart.
const Rendered = struct { texture: rl.Texture2D, px: i32 };
var rendered: [svgs.len][2]?Rendered = @splat(.{ null, null });

extern fn svgRasterize(data: [*]const u8, len: usize, px: c_int) ?[*]u8;
extern fn svgFree(pixels: [*]u8) void;

fn texture(icon: Icon, open: bool, px: i32) ?rl.Texture2D {
    const slot = &rendered[@intFromEnum(icon)][@intFromBool(open)];
    if (slot.*) |r| {
        if (r.px == px) return r.texture;
        rl.unloadTexture(r.texture);
        slot.* = null;
    }
    const svg = if (open) svgs[@intFromEnum(icon)].open else svgs[@intFromEnum(icon)].shut;
    const pixels = svgRasterize(svg.ptr, svg.len, px) orelse return null;
    defer svgFree(pixels);
    const image: rl.Image = .{ .data = pixels, .width = px, .height = px, .mipmaps = 1, .format = .uncompressed_r8g8b8a8 };
    const t = rl.loadTextureFromImage(image) catch return null;
    rl.setTextureFilter(t, .bilinear);
    slot.* = .{ .texture = t, .px = px };
    return t;
}

/// Draws the icon for the folder `name` centered at `center`. `open` is
/// how far it has opened: the shut and open shapes cross over between 0
/// and 1, so an opening folder doesn't snap from one to the other.
pub fn draw(name: []const u8, open: f32, center: rl.Vector2) void {
    if (mode == .none) return;
    const t = std.math.clamp(open, 0, 1);
    const icon = iconFor(name);
    if (t < 1) drawOne(icon, false, center, 1 - t);
    if (t > 0) drawOne(icon, true, center, t);
}

fn drawOne(icon: Icon, open: bool, center: rl.Vector2, alpha: f32) void {
    // Screen pixels per UI unit: display density times zoom.
    const scale = @max(1, rl.getWindowScaleDPI().x) * theme.zoom;
    const px: i32 = @intFromFloat(@round(size * scale));
    const t = texture(icon, open, px) orelse return;
    const pixel = 1 / scale;
    const dest: rl.Rectangle = .{
        .x = @round((center.x - size / 2) / pixel) * pixel,
        .y = @round((center.y - size / 2) / pixel) * pixel,
        .width = size,
        .height = size,
    };
    const side: f32 = @floatFromInt(px);
    const tint: rl.Color = .{ .r = 255, .g = 255, .b = 255, .a = @intFromFloat(@round(std.math.clamp(alpha, 0, 1) * 255)) };
    rl.drawTexturePro(t, .{ .x = 0, .y = 0, .width = side, .height = side }, dest, .{ .x = 0, .y = 0 }, 0, tint);
}

/// Frees the rasterized icons (before the window closes).
pub fn unload() void {
    for (&rendered) |*pair| for (pair) |*slot| if (slot.*) |r| {
        rl.unloadTexture(r.texture);
        slot.* = null;
    };
}
